export const JsonData = [
  {
    id: 1,
    firstName: "Cad",
    lastName: "Ovendon",
    contactType: "email",
    contact: "covendon0@vinaora.com",
    DoB: "23/4/1994",
  },
  {
    id: 2,
    firstName: "Aretha",
    lastName: "Pellitt",
    contactType: "email",
    contact: "apellitt1@joomla.org",
    DoB: "14/11/2011",
  },
  {
    id: 3,
    firstName: "Jemmie",
    lastName: "Vost",
    contactType: "email",
    contact: "jvost2@cisco.com",
    DoB: "7/6/2011",
  },
  {
    id: 4,
    firstName: "Fancie",
    lastName: "Claige",
    contactType: "email",
    contact: "fclaige3@meetup.com",
    DoB: "18/2/1996",
  },
  {
    id: 5,
    firstName: "Audie",
    lastName: "Summerson",
    contactType: "email",
    contact: "asummerson4@plala.or.jp",
    DoB: "26/2/1998",
  },
  {
    id: 6,
    firstName: "Stavro",
    lastName: "Steuart",
    contactType: "email",
    contact: "ssteuart5@nhs.uk",
    DoB: "29/1/2017",
  },
  {
    id: 7,
    firstName: "Adrienne",
    lastName: "Amner",
    contactType: "email",
    contact: "aamner6@wordpress.com",
    DoB: "12/11/1990",
  },
  {
    id: 8,
    firstName: "Travers",
    lastName: "Loxston",
    contactType: "email",
    contact: "tloxston7@epa.gov",
    DoB: "16/7/2015",
  },
  {
    id: 9,
    firstName: "Leonhard",
    lastName: "Clapson",
    contactType: "email",
    contact: "lclapson8@sun.com",
    DoB: "11/11/2000",
  },
  {
    id: 10,
    firstName: "Alain",
    lastName: "Sprowle",
    contactType: "email",
    contact: "asprowle9@dailymail.co.uk",
    DoB: "13/5/2015",
  },
];
